export const quotes = [
    { content: "Typography is what language looks like.", author: "Ellen Lupton" },
    { content: "Type is a beautiful group of letters, not a group of beautiful letters.", author: "Matthew Carter" },
    { content: "Good typography is invisible, bad typography is everywhere.", author: "Frank Chimero" },
    { content: "Typography has one plain duty before it and that is to convey information in writing.", author: "Emil Ruder" },
    { content: "There are now about as many different varieties of letters as there are different kinds of fools.", author: "Eric Gill" },
    { content: "Typography is two-dimensional architecture.", author: "Hermann Zapf" },
    { content: "Typography is to literature what musical performance is to composition: an essential act of interpretation.", author: "Robert Bringhurst" },
    { content: "Words have meaning. Type has spirit. The combination is spectacular.", author: "Paula Scher" },
    { content: "The crystal goblet: it is meant to reveal rather than hide the beautiful thing which it was meant to contain.", author: "Beatrice Warde" },
    { content: "Type is a voice; its message comes across loud and unclear.", author: "Ellen Lupton" },
    { content: "If you remember the shape of your spoon at lunch, it has to be the wrong shape.", author: "Adrian Frutiger" },
    { content: "A typeface is an alphabet in a straitjacket.", author: "Alan Fletcher" },
    { content: "Typography is a hidden tool of manipulation within society.", author: "Neville Brody" },
    { content: "God is in the details.", author: "Mies van der Rohe" },
    { content: "Typography at its best is a visual form of language linking timelessness and time.", author: "Robert Bringhurst" },
    { content: "Typography is the craft of endowing human language with a durable visual form.", author: "Robert Bringhurst" },
    { content: "Every typeface is a piece of history.", author: "Adrian Frutiger" },
    { content: "The details are not the details. They make the design.", author: "Charles Eames" },
    { content: "Reading is a linear activity, but typography gives reading a multidimensional life.", author: "Cyrus Highsmith" },
    { content: "Typography is the detail and the presentation of a story.", author: "Cyrus Highsmith" },
    { content: "The discipline of typography is the discipline of reading.", author: "Erik Spiekermann" },
    { content: "A man who would letterspace lowercase would steal sheep.", author: "Frederic Goudy" },
    { content: "Type well used is invisible as type, just as the perfect talking voice is the unnoticed vehicle for the transmission of words, ideas.", author: "Beatrice Warde" },
    { content: "Fonts are like shoes. Beautiful shoes that don't fit are useless.", author: "Tobias Frere-Jones" },
    { content: "Typographic design should perform optically what the speaker creates through voice and gesture of his thoughts.", author: "El Lissitzky" },
    { content: "The absence of a solution is not the absence of an answer.", author: "Jonathan Hoefler" },
    { content: "Sometimes you have to get the client to look at the solution, not the problem.", author: "Massimo Vignelli" },
    { content: "Letters are microscopic works of art.", author: "Alina Wheeler" },
    { content: "Typography is a public utility.", author: "Otl Aicher" },
    { content: "Typography is what makes or breaks design.", author: "Massimo Vignelli" },
    { content: "Typography exists to honor content.", author: "Robert Bringhurst" },
    { content: "Legibility never provokes thought, it's too busy being legible.", author: "David Carson" },
    { content: "The whole point of good typography is that the reader doesn't notice it.", author: "Beatrice Warde" },
    { content: "Type is a beautiful group of letters, not a group of beautiful letters.", author: "Matthew Carter" },
    { content: "Typography is the craft of endowing human language with a durable visual form.", author: "Robert Bringhurst" },
    { content: "Typography is the art and technique of arranging type to make written language legible, readable, and appealing when displayed.", author: "Wikipedia" },
    { content: "Typography is the craft of endowing human language with a durable visual form.", author: "Robert Bringhurst" },
    { content: "Type is a beautiful group of letters, not a group of beautiful letters.", author: "Matthew Carter" },
    { content: "Typography is what language looks like.", author: "Ellen Lupton" },
    { content: "Good typography is invisible, bad typography is everywhere.", author: "Frank Chimero" },
    { content: "Typography has one plain duty before it and that is to convey information in writing.", author: "Emil Ruder" },
    { content: "There are now about as many different varieties of letters as there are different kinds of fools.", author: "Eric Gill" },
    { content: "Typography is two-dimensional architecture.", author: "Hermann Zapf" },
    { content: "Typography is to literature what musical performance is to composition: an essential act of interpretation.", author: "Robert Bringhurst" },
    { content: "Words have meaning. Type has spirit. The combination is spectacular.", author: "Paula Scher" },
    { content: "The crystal goblet: it is meant to reveal rather than hide the beautiful thing which it was meant to contain.", author: "Beatrice Warde" },
    { content: "Type is a voice; its message comes across loud and unclear.", author: "Ellen Lupton" },
    { content: "If you remember the shape of your spoon at lunch, it has to be the wrong shape.", author: "Adrian Frutiger" },
    { content: "A typeface is an alphabet in a straitjacket.", author: "Alan Fletcher" },
    { content: "Typography is a hidden tool of manipulation within society.", author: "Neville Brody" },
    { content: "God is in the details.", author: "Mies van der Rohe" },
    { content: "Typography at its best is a visual form of language linking timelessness and time.", author: "Robert Bringhurst" },
    { content: "Typography is the craft of endowing human language with a durable visual form.", author: "Robert Bringhurst" },
    { content: "Every typeface is a piece of history.", author: "Adrian Frutiger" },
    { content: "The details are not the details. They make the design.", author: "Charles Eames" }
];
